### ISSUE TITLE
Epic: Price Feeder V1

### ISSUE THREAD

**Issue by adamewozniak** [ojo-network/price-feeder#1]
## Summary

We need to set up a repo for the price feeder on Ojo

- [x] ojo-network/ojo#45
- [x] #2
- [x] #3
- [x] #4
- [x] #5
- [x] #10
- [x] #20
- [x] #9
- [x] #33
- [x] #34
- [x] #47

---

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by adamewozniak** [comment]
Note that we've planned not to make this agnostic for now, unless the price feeder on here & umee get super difficult to maintain. 

Main priority should be bringing this repo up to snuff with umee's price feeder as far as tests & docs
